# Generated by Django 4.2.5 on 2023-09-08 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vendor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('password', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'vendors',
            },
        ),
    ]
