# Generated by Django 4.2.5 on 2023-09-09 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_socialmediahandles_vendors_venue_venuebookings_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vendors',
        ),
    ]
