# Generated by Django 4.2.5 on 2023-09-09 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_delete_vendors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendors',
            fields=[
                ('vendor_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('contact_information', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('vendor_type', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('products_or_services', models.TextField(blank=True, default=None, null=True)),
                ('address', models.TextField(blank=True, default=None, null=True)),
                ('website', models.URLField(blank=True, default=None, null=True)),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('availability', models.BooleanField(default=False)),
                ('insurance_coverage', models.TextField(blank=True, default=None, null=True)),
                ('licenses_and_permits', models.TextField(blank=True, default=None, null=True)),
                ('preferred_venues', models.TextField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'vendors',
            },
        ),
    ]
