# Generated by Django 4.2.5 on 2023-09-10 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_vendors'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorPhoto',
            fields=[
                ('vendor_photo_id', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.ImageField(upload_to='vendor_photos/')),
            ],
            options={
                'db_table': 'vendor_photos',
            },
        ),
        migrations.CreateModel(
            name='VendorType',
            fields=[
                ('vendor_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'vendor_types',
            },
        ),
        migrations.CreateModel(
            name='VenuePhoto',
            fields=[
                ('venue_photo_id', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.ImageField(upload_to='venue_photos/')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.venue')),
            ],
            options={
                'db_table': 'venue_photos',
            },
        ),
        migrations.RenameField(
            model_name='vendors',
            old_name='contact_information',
            new_name='contact_email',
        ),
        migrations.RemoveField(
            model_name='venueevents',
            name='videos_from_past_events',
        ),
        migrations.AddField(
            model_name='vendors',
            name='city',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='venueevents',
            name='photos_from_past_events',
        ),
        migrations.DeleteModel(
            name='VenuePreferredVendors',
        ),
        migrations.AddField(
            model_name='vendorphoto',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.vendors'),
        ),
        migrations.AddField(
            model_name='vendors',
            name='photos',
            field=models.ManyToManyField(blank=True, to='apis.vendorphoto'),
        ),
        migrations.AlterField(
            model_name='vendors',
            name='vendor_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apis.vendortype'),
        ),
        migrations.AddField(
            model_name='venueevents',
            name='photos_from_past_events',
            field=models.ManyToManyField(blank=True, to='apis.venuephoto'),
        ),
    ]
