# Generated by Django 4.2.5 on 2023-09-10 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0009_cities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendors',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apis.cities'),
        ),
    ]
