# Generated by Django 4.2.5 on 2023-09-11 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0010_alter_vendors_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendors',
            name='photos',
        ),
        migrations.DeleteModel(
            name='VendorPhotos',
        ),
        migrations.AddField(
            model_name='vendors',
            name='photos',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
