# Generated by Django 4.2.5 on 2023-09-11 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0011_remove_vendors_photos_delete_vendorphotos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendors',
            name='photos',
        ),
        migrations.CreateModel(
            name='VendorPhotos',
            fields=[
                ('vendor_photo_id', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.ImageField(upload_to='vendor_photos/')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.vendors')),
            ],
            options={
                'db_table': 'vendor_photos',
            },
        ),
        migrations.AddField(
            model_name='vendors',
            name='photos',
            field=models.ManyToManyField(blank=True, to='apis.vendorphotos'),
        ),
    ]
