# Generated by Django 4.2.5 on 2023-09-11 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0012_remove_vendors_photos_vendorphotos_vendors_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendors',
            name='photos',
        ),
    ]
