# Generated by Django 4.2.5 on 2023-09-11 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0014_vendors_photo_delete_vendorphotos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendors',
            name='photo',
        ),
        migrations.CreateModel(
            name='VendorPhotos',
            fields=[
                ('vendor_photo_id', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.ImageField(upload_to='vendor_photos/')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.vendors')),
            ],
            options={
                'db_table': 'vendor_photos',
            },
        ),
    ]
